<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mulai Berinvestasi</name>
   <tag></tag>
   <elementGuidId>b46f16e2-fd62-4074-8e4a-65ac3e619d61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.home-btn.start-investing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section0']/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25e78499-ed1b-4d8f-900e-921563197527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-btn start-investing</value>
      <webElementGuid>d0b395aa-7a26-4ea8-b29a-c124cf32504b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://stockbit.com/#/register</value>
      <webElementGuid>a0fb8a7c-1b12-4eb0-8f48-6f166e49bace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>7cbb5580-c68f-4e7b-a0db-448e2b7d4518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mulai Berinvestasi</value>
      <webElementGuid>89d1936a-7ace-4496-a935-7e6bb3644a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section0&quot;)/div[@class=&quot;fp-tableCell&quot;]/div[@class=&quot;insider fclear homepage&quot;]/div[@class=&quot;content-left content-big&quot;]/div[@class=&quot;content-in&quot;]/a[@class=&quot;home-btn start-investing&quot;]</value>
      <webElementGuid>0616f05b-0aba-414e-9b03-07e9e2e135f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section0']/div/div/div/div/a</value>
      <webElementGuid>a83eb894-1c32-4ef6-a22e-db5d0048a594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mulai Berinvestasi')]</value>
      <webElementGuid>c1d48f86-6e65-44b2-9b9a-1e88ace47c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluarga'])[1]/following::a[1]</value>
      <webElementGuid>7ddd0457-ff11-4b17-be8d-dd8a472b24bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teman'])[1]/following::a[1]</value>
      <webElementGuid>d17648ac-68b8-4477-8207-2fbfeb00bd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaya Komisi'])[1]/preceding::a[3]</value>
      <webElementGuid>fef90b42-bdd3-4ea7-afee-f542a323ccbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fee Beli'])[1]/preceding::a[3]</value>
      <webElementGuid>c980fac9-970f-48b3-949e-6315a07b26f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mulai Berinvestasi']/parent::*</value>
      <webElementGuid>0c57ecb9-acbd-4be3-ab5e-d4ca52382bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://stockbit.com/#/register')])[3]</value>
      <webElementGuid>48d0190e-0b62-4692-bda7-4f6a517098bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/a</value>
      <webElementGuid>543d1852-8ccc-4f4a-8d27-130df130ca51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://stockbit.com/#/register' and (text() = 'Mulai Berinvestasi' or . = 'Mulai Berinvestasi')]</value>
      <webElementGuid>2fc0fce8-66f0-4caf-b474-9df5e103d586</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
