<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>0a29c154-b83d-4044-81d3-ebe994bde494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section0']/div/div/div/div/div[3]/a[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a83cb87a-5929-4de5-81a8-a91f2b2060de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://stockbit.com/assets/template/f06b908907d5.png</value>
      <webElementGuid>86410868-0e84-46f8-b426-59d019208ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section0&quot;)/div[@class=&quot;fp-tableCell&quot;]/div[@class=&quot;insider fclear homepage&quot;]/div[@class=&quot;content-left content-big&quot;]/div[@class=&quot;content-in&quot;]/div[@class=&quot;home-badges depan&quot;]/a[2]/img[1]</value>
      <webElementGuid>24907500-d0ef-47b6-b1d8-619c0609bcc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section0']/div/div/div/div/div[3]/a[2]/img</value>
      <webElementGuid>72eebbda-9b9f-419c-a30e-aff32335fa00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://stockbit.com/assets/template/f06b908907d5.png')]</value>
      <webElementGuid>d5a1f052-48f1-431d-ac9f-026eed1c4edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>c1d13aeb-e4e7-4bf0-a223-804978775ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://stockbit.com/assets/template/f06b908907d5.png']</value>
      <webElementGuid>0b41cd9a-8c2c-46ff-9e67-af9449fabb0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
