<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buka Rekening Anda</name>
   <tag></tag>
   <elementGuidId>a04ca12e-8046-4667-98be-11e5c27646c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.styled__ButtonRegister-cawzx3-3.RRMCy.scaleUpX.scaleUp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b81ba66-aad4-4b77-bb36-2dbe144018ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__ButtonRegister-cawzx3-3 RRMCy scaleUpX scaleUp</value>
      <webElementGuid>4d880548-379b-4e7f-bc90-ea01318ccc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>b2c1d606-a191-4827-93f6-56dd9ae72dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>84547344-5c54-4706-9d03-392b1dda24b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/register</value>
      <webElementGuid>a60da390-3091-46a8-a102-4fab8b011532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buka Rekening Anda</value>
      <webElementGuid>e19a121f-6ef2-4a58-ad1c-926b9d9d4be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styled__ContentWrapper-xns5g1-0 jfHzrO&quot;]/div[@class=&quot;styled__FullPage-xns5g1-9 vcuOF&quot;]/div[@class=&quot;sc-gKAaRy styled__Wrapper-cawzx3-0 dBMrnV dbpnDt&quot;]/a[@class=&quot;styled__ButtonRegister-cawzx3-3 RRMCy scaleUpX scaleUp&quot;]</value>
      <webElementGuid>53c90fde-60f7-418c-a988-911c4254e40b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/a</value>
      <webElementGuid>0f70514d-28a4-4b40-9e74-3c8fa8b61a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Buka Rekening Anda')]</value>
      <webElementGuid>16c9b421-fc16-4bb8-8bd7-b8eaac6ad968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PE Standard Deviation Band'])[1]/following::a[1]</value>
      <webElementGuid>469fa3bb-e9a9-409e-9e3d-d315bc5ed513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Finansial yang Lengkap'])[1]/following::a[1]</value>
      <webElementGuid>4edd62c0-3fbf-4969-9b92-599c4fac92f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi &amp; Persyaratan Layanan Stockbit'])[1]/preceding::a[1]</value>
      <webElementGuid>14ec79b5-54c3-4919-bd27-0507af23d373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequently Asked Questions'])[1]/preceding::a[2]</value>
      <webElementGuid>486c5cb5-7c92-423b-9666-c3f0fe2f9191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buka Rekening Anda']/parent::*</value>
      <webElementGuid>440bf999-6651-4c6b-8656-24ba7bd9ee2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/register')]</value>
      <webElementGuid>f6c5888a-dcc4-4de2-a2ea-6541dcb30458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>6a0dcd89-b8be-4b86-9906-e4d41a1140dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/register' and (text() = 'Buka Rekening Anda' or . = 'Buka Rekening Anda')]</value>
      <webElementGuid>1953d2a6-0a05-4d19-915b-f30dfe9d8f15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
