<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>f1c30cea-f39a-4d70-b091-aa2080b077e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-fXeWgy.iCxvLv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='borderPrimary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3386d7ad-0c2b-438a-bd94-4c04cb2e83d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>7455ab25-e0cd-4094-ba98-70a127476144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>16px</value>
      <webElementGuid>c6e049d3-da84-4b58-9009-17fa4dee5dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>borderPrimary</value>
      <webElementGuid>0ca85fb6-5ad0-444e-a8d8-9ddb2eca9174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>36px</value>
      <webElementGuid>3548f752-0ac6-4ce1-bf12-1e34bb285c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120px</value>
      <webElementGuid>a73bc425-835a-46b0-bdd5-412aa6521d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fXeWgy iCxvLv</value>
      <webElementGuid>f75be191-f61f-431b-b21c-8aa6c1ce2470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>af65b076-ef0d-425d-8466-949bd04bc371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/header[@class=&quot;sc-fXEqXD sc-haTkCf egxbtU jpoSLZ&quot;]/div[@class=&quot;sc-cfJNbs dZAkTy&quot;]/div[@class=&quot;sc-bLdsei dNmqyz&quot;]/button[@class=&quot;sc-fXeWgy iCxvLv&quot;]</value>
      <webElementGuid>5029c2e9-0ed4-46e4-88c0-04cd01795063</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='borderPrimary']</value>
      <webElementGuid>b67e5d0a-8a49-4ede-8426-e9cdedbce199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div[2]/button</value>
      <webElementGuid>03533ad5-964a-436b-be01-560b0ae47606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::button[1]</value>
      <webElementGuid>27ccee5e-78b5-4be8-b844-e31101687d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockbit Academy'])[1]/preceding::button[2]</value>
      <webElementGuid>0aeb7a7d-b578-4d48-b176-38652460f466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>1232e009-68b6-47bf-8509-a9349f342589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>34e51993-08c5-46cd-bb44-c2679a1623f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'borderPrimary' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>d2351a1f-d48e-4762-83dc-0aac68a73765</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
