<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search on Helpdesk</name>
   <tag></tag>
   <elementGuidId>5beae63d-a55a-4b85-8d5c-56aa5ef9d8a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cc-13ft.cc-ujki.cc-co2u</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='crisp-chatbox']/div/div/div[2]/div/div[3]/div/div/div/div/span[2]/span/span/span/span/span/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c6988ed-2d24-49b0-a635-67b3885e169f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>6f9f35c9-059f-4907-8704-322f79f5832d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>72ddc6cc-849d-43e4-997d-1119a8236ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>1f729ed7-8501-4b7d-9ff0-7fce2e2e15ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cc-13ft cc-ujki cc-co2u</value>
      <webElementGuid>fbc440d4-b504-4ad2-b05b-ce0338d679bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://help.stockbit.com/</value>
      <webElementGuid>7d082515-5270-42eb-9752-baa6dbefbd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>helpdesk</value>
      <webElementGuid>6d7622be-aa3a-43fa-a4b9-37ddd9121ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search on Helpdesk</value>
      <webElementGuid>17012556-3326-4212-955a-654e2ad473f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crisp-chatbox&quot;)/div[@class=&quot;cc-kegp cc-xh3e&quot;]/div[@class=&quot;cc-1apq&quot;]/div[@class=&quot;cc-1jpm&quot;]/div[@class=&quot;cc-ggw8&quot;]/div[@class=&quot;cc-x5kk cc-qovj&quot;]/div[@class=&quot;cc-301t&quot;]/div[@class=&quot;cc-hh0f wp-exclude-emoji&quot;]/div[@class=&quot;cc-1yoz&quot;]/div[@class=&quot;cc-146d&quot;]/span[@class=&quot;cc-914h cc-25ir&quot;]/span[@class=&quot;cc-1fd5 cc-z2in cc-1s3d&quot;]/span[@class=&quot;cc-70ck cc-18hf cc-guf7&quot;]/span[@class=&quot;cc-1k9b&quot;]/span[@class=&quot;cc-c88o&quot;]/span[@class=&quot;cc-12al&quot;]/span[@class=&quot;cc-wspd&quot;]/a[@class=&quot;cc-13ft cc-ujki cc-co2u&quot;]</value>
      <webElementGuid>5615d9f6-bb93-46b4-be81-52c67a0d0122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='crisp-chatbox']/div/div/div[2]/div/div[3]/div/div/div/div/span[2]/span/span/span/span/span/span/a</value>
      <webElementGuid>f26f2485-4034-45db-a755-d9e42f53a0ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Search on Helpdesk')]</value>
      <webElementGuid>f2192a71-64a4-4ab8-8682-256959518e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello! How can I help you?'])[1]/following::a[1]</value>
      <webElementGuid>7de2731f-b1f0-42fb-b9d1-2c9b715584ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stockbit'])[2]/following::a[1]</value>
      <webElementGuid>f1c819f8-16ab-4c85-af12-a83591f3f17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send a file'])[1]/preceding::a[1]</value>
      <webElementGuid>013cb2ae-1109-4578-a5f4-8c7c3a5057a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert an emoji'])[1]/preceding::a[1]</value>
      <webElementGuid>04cd3064-a852-4809-9088-28635e0a1751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://help.stockbit.com/')])[2]</value>
      <webElementGuid>e30e99db-e1a4-4e68-9a8e-a0d41f9da25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/a</value>
      <webElementGuid>26f6998d-b9d7-4f19-8c72-2446a92bbb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://help.stockbit.com/' and (text() = 'Search on Helpdesk' or . = 'Search on Helpdesk')]</value>
      <webElementGuid>e0aad2d6-0af0-41d0-9b4f-431bbb122a0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
